// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.1
// source: proto/yukon.proto

package yukon

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// A probe is addressed on the wire as (class_id, probe_index) rather than a
// flat global ID: class_id is assigned once per (service, version) and
// carried in ProbeManifest, so delta batches don't repeat fully-qualified
// class names on every flush.
type ProbeKind int32

const (
	ProbeKind_PROBE_KIND_UNSPECIFIED ProbeKind = 0
	ProbeKind_METHOD                 ProbeKind = 1
	ProbeKind_BRANCH                 ProbeKind = 2
)

// Enum value maps for ProbeKind.
var (
	ProbeKind_name = map[int32]string{
		0: "PROBE_KIND_UNSPECIFIED",
		1: "METHOD",
		2: "BRANCH",
	}
	ProbeKind_value = map[string]int32{
		"PROBE_KIND_UNSPECIFIED": 0,
		"METHOD":                 1,
		"BRANCH":                 2,
	}
)

func (x ProbeKind) Enum() *ProbeKind {
	p := new(ProbeKind)
	*p = x
	return p
}

func (x ProbeKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProbeKind) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_yukon_proto_enumTypes[0].Descriptor()
}

func (ProbeKind) Type() protoreflect.EnumType {
	return &file_proto_yukon_proto_enumTypes[0]
}

func (x ProbeKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProbeKind.Descriptor instead.
func (ProbeKind) EnumDescriptor() ([]byte, []int) {
	return file_proto_yukon_proto_rawDescGZIP(), []int{0}
}

type ResourceAttributes struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ServiceName       string                 `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	ServiceVersion    *string                `protobuf:"bytes,2,opt,name=service_version,json=serviceVersion,proto3,oneof" json:"service_version,omitempty"`
	ServiceInstanceId string                 `protobuf:"bytes,3,opt,name=service_instance_id,json=serviceInstanceId,proto3" json:"service_instance_id,omitempty"`
	Environment       *string                `protobuf:"bytes,4,opt,name=environment,proto3,oneof" json:"environment,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ResourceAttributes) Reset() {
	*x = ResourceAttributes{}
	mi := &file_proto_yukon_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceAttributes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceAttributes) ProtoMessage() {}

func (x *ResourceAttributes) ProtoReflect() protoreflect.Message {
	mi := &file_proto_yukon_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceAttributes.ProtoReflect.Descriptor instead.
func (*ResourceAttributes) Descriptor() ([]byte, []int) {
	return file_proto_yukon_proto_rawDescGZIP(), []int{0}
}

func (x *ResourceAttributes) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *ResourceAttributes) GetServiceVersion() string {
	if x != nil && x.ServiceVersion != nil {
		return *x.ServiceVersion
	}
	return ""
}

func (x *ResourceAttributes) GetServiceInstanceId() string {
	if x != nil {
		return x.ServiceInstanceId
	}
	return ""
}

func (x *ResourceAttributes) GetEnvironment() string {
	if x != nil && x.Environment != nil {
		return *x.Environment
	}
	return ""
}

type ProbeDelta struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	ClassId            int32                  `protobuf:"varint,1,opt,name=class_id,json=classId,proto3" json:"class_id,omitempty"`
	ProbeIndex         int32                  `protobuf:"varint,2,opt,name=probe_index,json=probeIndex,proto3" json:"probe_index,omitempty"`
	Kind               ProbeKind              `protobuf:"varint,3,opt,name=kind,proto3,enum=yukon.ProbeKind" json:"kind,omitempty"`
	FirstSeenAt        int64                  `protobuf:"varint,4,opt,name=first_seen_at,json=firstSeenAt,proto3" json:"first_seen_at,omitempty"`
	HitsSinceLastFlush int64                  `protobuf:"varint,5,opt,name=hits_since_last_flush,json=hitsSinceLastFlush,proto3" json:"hits_since_last_flush,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ProbeDelta) Reset() {
	*x = ProbeDelta{}
	mi := &file_proto_yukon_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProbeDelta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProbeDelta) ProtoMessage() {}

func (x *ProbeDelta) ProtoReflect() protoreflect.Message {
	mi := &file_proto_yukon_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProbeDelta.ProtoReflect.Descriptor instead.
func (*ProbeDelta) Descriptor() ([]byte, []int) {
	return file_proto_yukon_proto_rawDescGZIP(), []int{1}
}

func (x *ProbeDelta) GetClassId() int32 {
	if x != nil {
		return x.ClassId
	}
	return 0
}

func (x *ProbeDelta) GetProbeIndex() int32 {
	if x != nil {
		return x.ProbeIndex
	}
	return 0
}

func (x *ProbeDelta) GetKind() ProbeKind {
	if x != nil {
		return x.Kind
	}
	return ProbeKind_PROBE_KIND_UNSPECIFIED
}

func (x *ProbeDelta) GetFirstSeenAt() int64 {
	if x != nil {
		return x.FirstSeenAt
	}
	return 0
}

func (x *ProbeDelta) GetHitsSinceLastFlush() int64 {
	if x != nil {
		return x.HitsSinceLastFlush
	}
	return 0
}

// Sent frequently (every 30-60s). Delta-only, not a full snapshot, so
// payload size stays independent of total probe count.
type DeltaBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resource      *ResourceAttributes    `protobuf:"bytes,1,opt,name=resource,proto3" json:"resource,omitempty"`
	Deltas        []*ProbeDelta          `protobuf:"bytes,2,rep,name=deltas,proto3" json:"deltas,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeltaBatch) Reset() {
	*x = DeltaBatch{}
	mi := &file_proto_yukon_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeltaBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeltaBatch) ProtoMessage() {}

func (x *DeltaBatch) ProtoReflect() protoreflect.Message {
	mi := &file_proto_yukon_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeltaBatch.ProtoReflect.Descriptor instead.
func (*DeltaBatch) Descriptor() ([]byte, []int) {
	return file_proto_yukon_proto_rawDescGZIP(), []int{2}
}

func (x *DeltaBatch) GetResource() *ResourceAttributes {
	if x != nil {
		return x.Resource
	}
	return nil
}

func (x *DeltaBatch) GetDeltas() []*ProbeDelta {
	if x != nil {
		return x.Deltas
	}
	return nil
}

type ProbeLocation struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ClassId          int32                  `protobuf:"varint,1,opt,name=class_id,json=classId,proto3" json:"class_id,omitempty"`
	ProbeIndex       int32                  `protobuf:"varint,2,opt,name=probe_index,json=probeIndex,proto3" json:"probe_index,omitempty"`
	Kind             ProbeKind              `protobuf:"varint,3,opt,name=kind,proto3,enum=yukon.ProbeKind" json:"kind,omitempty"`
	ClassName        string                 `protobuf:"bytes,4,opt,name=class_name,json=className,proto3" json:"class_name,omitempty"`
	MethodName       string                 `protobuf:"bytes,5,opt,name=method_name,json=methodName,proto3" json:"method_name,omitempty"`
	MethodDescriptor string                 `protobuf:"bytes,6,opt,name=method_descriptor,json=methodDescriptor,proto3" json:"method_descriptor,omitempty"`
	Line             int32                  `protobuf:"varint,7,opt,name=line,proto3" json:"line,omitempty"`
	// Unset for method-level probes; set for branch-level probes.
	BranchIndex   *int32 `protobuf:"varint,8,opt,name=branch_index,json=branchIndex,proto3,oneof" json:"branch_index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProbeLocation) Reset() {
	*x = ProbeLocation{}
	mi := &file_proto_yukon_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProbeLocation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProbeLocation) ProtoMessage() {}

func (x *ProbeLocation) ProtoReflect() protoreflect.Message {
	mi := &file_proto_yukon_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProbeLocation.ProtoReflect.Descriptor instead.
func (*ProbeLocation) Descriptor() ([]byte, []int) {
	return file_proto_yukon_proto_rawDescGZIP(), []int{3}
}

func (x *ProbeLocation) GetClassId() int32 {
	if x != nil {
		return x.ClassId
	}
	return 0
}

func (x *ProbeLocation) GetProbeIndex() int32 {
	if x != nil {
		return x.ProbeIndex
	}
	return 0
}

func (x *ProbeLocation) GetKind() ProbeKind {
	if x != nil {
		return x.Kind
	}
	return ProbeKind_PROBE_KIND_UNSPECIFIED
}

func (x *ProbeLocation) GetClassName() string {
	if x != nil {
		return x.ClassName
	}
	return ""
}

func (x *ProbeLocation) GetMethodName() string {
	if x != nil {
		return x.MethodName
	}
	return ""
}

func (x *ProbeLocation) GetMethodDescriptor() string {
	if x != nil {
		return x.MethodDescriptor
	}
	return ""
}

func (x *ProbeLocation) GetLine() int32 {
	if x != nil {
		return x.Line
	}
	return 0
}

func (x *ProbeLocation) GetBranchIndex() int32 {
	if x != nil && x.BranchIndex != nil {
		return *x.BranchIndex
	}
	return 0
}

// A class the agent matched but could not instrument (e.g. bytecode
// ByteBuddy refuses to redefine), so it never gets a class_id or any probes.
// Reported by name rather than class_id for exactly that reason: it never
// enters the class_id-assigning path a successfully instrumented class does.
type SkippedClass struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClassName     string                 `protobuf:"bytes,1,opt,name=class_name,json=className,proto3" json:"class_name,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	SkippedAt     int64                  `protobuf:"varint,3,opt,name=skipped_at,json=skippedAt,proto3" json:"skipped_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SkippedClass) Reset() {
	*x = SkippedClass{}
	mi := &file_proto_yukon_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SkippedClass) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SkippedClass) ProtoMessage() {}

func (x *SkippedClass) ProtoReflect() protoreflect.Message {
	mi := &file_proto_yukon_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SkippedClass.ProtoReflect.Descriptor instead.
func (*SkippedClass) Descriptor() ([]byte, []int) {
	return file_proto_yukon_proto_rawDescGZIP(), []int{4}
}

func (x *SkippedClass) GetClassName() string {
	if x != nil {
		return x.ClassName
	}
	return ""
}

func (x *SkippedClass) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *SkippedClass) GetSkippedAt() int64 {
	if x != nil {
		return x.SkippedAt
	}
	return 0
}

// Sent once per (service, version), not per flush, so the collector can
// resolve probe IDs to source locations without the agent repeating this
// metadata on every delta batch.
type ProbeManifest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ServiceName    string                 `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	ServiceVersion *string                `protobuf:"bytes,2,opt,name=service_version,json=serviceVersion,proto3,oneof" json:"service_version,omitempty"`
	Probes         []*ProbeLocation       `protobuf:"bytes,3,rep,name=probes,proto3" json:"probes,omitempty"`
	SkippedClasses []*SkippedClass        `protobuf:"bytes,4,rep,name=skipped_classes,json=skippedClasses,proto3" json:"skipped_classes,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ProbeManifest) Reset() {
	*x = ProbeManifest{}
	mi := &file_proto_yukon_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProbeManifest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProbeManifest) ProtoMessage() {}

func (x *ProbeManifest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_yukon_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProbeManifest.ProtoReflect.Descriptor instead.
func (*ProbeManifest) Descriptor() ([]byte, []int) {
	return file_proto_yukon_proto_rawDescGZIP(), []int{5}
}

func (x *ProbeManifest) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *ProbeManifest) GetServiceVersion() string {
	if x != nil && x.ServiceVersion != nil {
		return *x.ServiceVersion
	}
	return ""
}

func (x *ProbeManifest) GetProbes() []*ProbeLocation {
	if x != nil {
		return x.Probes
	}
	return nil
}

func (x *ProbeManifest) GetSkippedClasses() []*SkippedClass {
	if x != nil {
		return x.SkippedClasses
	}
	return nil
}

var File_proto_yukon_proto protoreflect.FileDescriptor

const file_proto_yukon_proto_rawDesc = "" +
	"\n" +
	"\x11proto/yukon.proto\x12\x05yukon\"\xe0\x01\n" +
	"\x12ResourceAttributes\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\x12,\n" +
	"\x0fservice_version\x18\x02 \x01(\tH\x00R\x0eserviceVersion\x88\x01\x01\x12.\n" +
	"\x13service_instance_id\x18\x03 \x01(\tR\x11serviceInstanceId\x12%\n" +
	"\venvironment\x18\x04 \x01(\tH\x01R\venvironment\x88\x01\x01B\x12\n" +
	"\x10_service_versionB\x0e\n" +
	"\f_environment\"\xc5\x01\n" +
	"\n" +
	"ProbeDelta\x12\x19\n" +
	"\bclass_id\x18\x01 \x01(\x05R\aclassId\x12\x1f\n" +
	"\vprobe_index\x18\x02 \x01(\x05R\n" +
	"probeIndex\x12$\n" +
	"\x04kind\x18\x03 \x01(\x0e2\x10.yukon.ProbeKindR\x04kind\x12\"\n" +
	"\rfirst_seen_at\x18\x04 \x01(\x03R\vfirstSeenAt\x121\n" +
	"\x15hits_since_last_flush\x18\x05 \x01(\x03R\x12hitsSinceLastFlush\"n\n" +
	"\n" +
	"DeltaBatch\x125\n" +
	"\bresource\x18\x01 \x01(\v2\x19.yukon.ResourceAttributesR\bresource\x12)\n" +
	"\x06deltas\x18\x02 \x03(\v2\x11.yukon.ProbeDeltaR\x06deltas\"\xab\x02\n" +
	"\rProbeLocation\x12\x19\n" +
	"\bclass_id\x18\x01 \x01(\x05R\aclassId\x12\x1f\n" +
	"\vprobe_index\x18\x02 \x01(\x05R\n" +
	"probeIndex\x12$\n" +
	"\x04kind\x18\x03 \x01(\x0e2\x10.yukon.ProbeKindR\x04kind\x12\x1d\n" +
	"\n" +
	"class_name\x18\x04 \x01(\tR\tclassName\x12\x1f\n" +
	"\vmethod_name\x18\x05 \x01(\tR\n" +
	"methodName\x12+\n" +
	"\x11method_descriptor\x18\x06 \x01(\tR\x10methodDescriptor\x12\x12\n" +
	"\x04line\x18\a \x01(\x05R\x04line\x12&\n" +
	"\fbranch_index\x18\b \x01(\x05H\x00R\vbranchIndex\x88\x01\x01B\x0f\n" +
	"\r_branch_index\"d\n" +
	"\fSkippedClass\x12\x1d\n" +
	"\n" +
	"class_name\x18\x01 \x01(\tR\tclassName\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12\x1d\n" +
	"\n" +
	"skipped_at\x18\x03 \x01(\x03R\tskippedAt\"\xe0\x01\n" +
	"\rProbeManifest\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\x12,\n" +
	"\x0fservice_version\x18\x02 \x01(\tH\x00R\x0eserviceVersion\x88\x01\x01\x12,\n" +
	"\x06probes\x18\x03 \x03(\v2\x14.yukon.ProbeLocationR\x06probes\x12<\n" +
	"\x0fskipped_classes\x18\x04 \x03(\v2\x13.yukon.SkippedClassR\x0eskippedClassesB\x12\n" +
	"\x10_service_version*?\n" +
	"\tProbeKind\x12\x1a\n" +
	"\x16PROBE_KIND_UNSPECIFIED\x10\x00\x12\n" +
	"\n" +
	"\x06METHOD\x10\x01\x12\n" +
	"\n" +
	"\x06BRANCH\x10\x02B<Z:github.com/LukeDevOps/yukon-collector/internal/proto/yukonb\x06proto3"

var (
	file_proto_yukon_proto_rawDescOnce sync.Once
	file_proto_yukon_proto_rawDescData []byte
)

func file_proto_yukon_proto_rawDescGZIP() []byte {
	file_proto_yukon_proto_rawDescOnce.Do(func() {
		file_proto_yukon_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_yukon_proto_rawDesc), len(file_proto_yukon_proto_rawDesc)))
	})
	return file_proto_yukon_proto_rawDescData
}

var file_proto_yukon_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_yukon_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_yukon_proto_goTypes = []any{
	(ProbeKind)(0),             // 0: yukon.ProbeKind
	(*ResourceAttributes)(nil), // 1: yukon.ResourceAttributes
	(*ProbeDelta)(nil),         // 2: yukon.ProbeDelta
	(*DeltaBatch)(nil),         // 3: yukon.DeltaBatch
	(*ProbeLocation)(nil),      // 4: yukon.ProbeLocation
	(*SkippedClass)(nil),       // 5: yukon.SkippedClass
	(*ProbeManifest)(nil),      // 6: yukon.ProbeManifest
}
var file_proto_yukon_proto_depIdxs = []int32{
	0, // 0: yukon.ProbeDelta.kind:type_name -> yukon.ProbeKind
	1, // 1: yukon.DeltaBatch.resource:type_name -> yukon.ResourceAttributes
	2, // 2: yukon.DeltaBatch.deltas:type_name -> yukon.ProbeDelta
	0, // 3: yukon.ProbeLocation.kind:type_name -> yukon.ProbeKind
	4, // 4: yukon.ProbeManifest.probes:type_name -> yukon.ProbeLocation
	5, // 5: yukon.ProbeManifest.skipped_classes:type_name -> yukon.SkippedClass
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_proto_yukon_proto_init() }
func file_proto_yukon_proto_init() {
	if File_proto_yukon_proto != nil {
		return
	}
	file_proto_yukon_proto_msgTypes[0].OneofWrappers = []any{}
	file_proto_yukon_proto_msgTypes[3].OneofWrappers = []any{}
	file_proto_yukon_proto_msgTypes[5].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_yukon_proto_rawDesc), len(file_proto_yukon_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_yukon_proto_goTypes,
		DependencyIndexes: file_proto_yukon_proto_depIdxs,
		EnumInfos:         file_proto_yukon_proto_enumTypes,
		MessageInfos:      file_proto_yukon_proto_msgTypes,
	}.Build()
	File_proto_yukon_proto = out.File
	file_proto_yukon_proto_goTypes = nil
	file_proto_yukon_proto_depIdxs = nil
}
